name = "hexxy_spade"

[synthesis]
top = "main"
command = "synth_ice40"

[pnr]
architecture = "ice40"
device = "iCE40HX8K"
pin_file = "cu.pcf"
package = "cb132"

[packing]
tool = "icepack"

[upload]
tool = "openFPGALoader"
board = "ice40_generic"

[libraries]
protocols.git = "https://codeberg.org/spade-lang/protocols.git"
